### ISSUE TITLE
Geen les vanavond (19 september): Richel is ziek

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/dojo#66]
@annehinrichs22
@antonhensen81
@AramPetiet
@binairgetal
@bitsaurus
@computerbaas
@daantje1
@Hans-Bouwman
@jesperdoekes
@Joshua260403
@kombossen
@martinicoder
@martje127
@mixmastermees
@ollyturner
@ProfRedRooster
@QuintinoM2
@RafayelGardishyan
@richelbilderbeek
@Rijk-van-Putten
@robkruger
@supergeleider
@SuperProgaMaker

**Comment by daantje1** [comment]
Gelukkig vandaag wel les @richelbilderbeek
Ik ben er niet bij
Ik heb een concert
Staan al een uur in de file
Yeah!

**Comment by richelbilderbeek** [comment]
@daantje1: hopelijk was het een leuk concert! Hopelijk tot volgende week, Richel

**Comment by daantje1** [comment]
ik denk dat je niet weer ziek bent

**Comment by daantje1** [comment]
zo

**Comment by richelbilderbeek** [comment]
Bedankt! :+1:
